export const states = [
  { id: 1, name: "Alabama", abbr: "AL" },
  { id: 2, name: "Alaska", abbr: "AK" },
  { id: 3, name: "Arizona", abbr: "AZ" },
  { id: 4, name: "Arkansas", abbr: "AR" },
  { id: 5, name: "California", abbr: "CA" },
  { id: 6, name: "Colorado", abbr: "CO" },
  { id: 7, name: "Connecticut", abbr: "CT" },
  { id: 8, name: "Delaware", abbr: "DE" },
  { id: 9, name: "Florida", abbr: "FL" },
  { id: 10, name: "Georgia", abbr: "GA" },
  { id: 11, name: "Hawaii", abbr: "HI" },
  { id: 12, name: "Idaho", abbr: "ID" },
  { id: 13, name: "Illinois", abbr: "IL" },
  { id: 14, name: "Indiana", abbr: "IN" },
  { id: 15, name: "Iowa", abbr: "IA" },
  { id: 16, name: "Kansas", abbr: "KS" },
  { id: 17, name: "Kentucky", abbr: "KY" },
  { id: 18, name: "Louisiana", abbr: "LA" },
  { id: 19, name: "Maine", abbr: "ME" },
  { id: 20, name: "Maryland", abbr: "MD" },
  { id: 21, name: "Massachusetts", abbr: "MA" },
  { id: 22, name: "Michigan", abbr: "MI" },
  { id: 23, name: "Minnesota", abbr: "MN" },
  { id: 24, name: "Mississippi", abbr: "MS" },
  { id: 25, name: "Missouri", abbr: "MO" },
  { id: 26, name: "Montana", abbr: "MT" },
  { id: 27, name: "Nebraska", abbr: "NE" },
  { id: 28, name: "Nevada", abbr: "NV" },
  { id: 29, name: "New Hampshire", abbr: "NH" },
  { id: 30, name: "New Jersey", abbr: "NJ" },
  { id: 31, name: "New Mexico", abbr: "NM" },
  { id: 32, name: "New York", abbr: "NY" },
  { id: 33, name: "North Carolina", abbr: "NC" },
  { id: 34, name: "North Dakota", abbr: "ND" },
  { id: 35, name: "Ohio", abbr: "OH" },
  { id: 36, name: "Oklahoma", abbr: "OK" },
  { id: 37, name: "Oregon", abbr: "OR" },
  { id: 38, name: "Pennsylvania", abbr: "PA" },
  { id: 39, name: "Rhode Island", abbr: "RI" },
  { id: 40, name: "South Carolina", abbr: "SC" },
  { id: 41, name: "South Dakota", abbr: "SD" },
  { id: 42, name: "Tennessee", abbr: "TN" },
  { id: 43, name: "Texas", abbr: "TX" },
  { id: 44, name: "Utah", abbr: "UT" },
  { id: 45, name: "Vermont", abbr: "VT" },
  { id: 46, name: "Virginia", abbr: "VA" },
  { id: 47, name: "Washington", abbr: "WA" },
  { id: 48, name: "West Virginia", abbr: "WV" },
  { id: 49, name: "Wisconsin", abbr: "WI" },
  { id: 50, name: "Wyoming", abbr: "WY" },
] as const;

export const cities = [
  { id: 1, name: "Montgomery", stateId: 1 },
  { id: 2, name: "Birmingham", stateId: 1 },
  { id: 3, name: "Huntsville", stateId: 1 },
  { id: 4, name: "Juneau", stateId: 2 },
  { id: 5, name: "Anchorage", stateId: 2 },
  { id: 6, name: "Fairbanks", stateId: 2 },
  { id: 7, name: "Phoenix", stateId: 3 },
  { id: 8, name: "Tucson", stateId: 3 },
  { id: 9, name: "Mesa", stateId: 3 },
  { id: 10, name: "Little Rock", stateId: 4 },
  { id: 11, name: "Fort Smith", stateId: 4 },
  { id: 12, name: "Fayetteville", stateId: 4 },
  { id: 13, name: "Los Angeles", stateId: 5 },
  { id: 14, name: "San Francisco", stateId: 5 },
  { id: 15, name: "San Diego", stateId: 5 },
  { id: 16, name: "Denver", stateId: 6 },
  { id: 17, name: "Colorado Springs", stateId: 6 },
  { id: 18, name: "Aurora", stateId: 6 },
  { id: 19, name: "Hartford", stateId: 7 },
  { id: 20, name: "New Haven", stateId: 7 },
  { id: 21, name: "Stamford", stateId: 7 },
  { id: 22, name: "Wilmington", stateId: 8 },
  { id: 23, name: "Dover", stateId: 8 },
  { id: 24, name: "Newark", stateId: 8 },
  { id: 25, name: "Jacksonville", stateId: 9 },
  { id: 26, name: "Miami", stateId: 9 },
  { id: 27, name: "Tampa", stateId: 9 },
  { id: 28, name: "Atlanta", stateId: 10 },
  { id: 29, name: "Augusta", stateId: 10 },
  { id: 30, name: "Columbus", stateId: 10 },
  { id: 31, name: "Honolulu", stateId: 11 },
  { id: 32, name: "Hilo", stateId: 11 },
  { id: 33, name: "Kailua", stateId: 11 },
  { id: 34, name: "Boise", stateId: 12 },
  { id: 35, name: "Nampa", stateId: 12 },
  { id: 36, name: "Meridian", stateId: 12 },
  { id: 37, name: "Chicago", stateId: 13 },
  { id: 38, name: "Aurora", stateId: 13 },
  { id: 39, name: "Rockford", stateId: 13 },
  { id: 40, name: "Indianapolis", stateId: 14 },
  { id: 41, name: "Fort Wayne", stateId: 14 },
  { id: 42, name: "Evansville", stateId: 14 },
  { id: 43, name: "Des Moines", stateId: 15 },
  { id: 44, name: "Cedar Rapids", stateId: 15 },
  { id: 45, name: "Davenport", stateId: 15 },
  { id: 46, name: "Wichita", stateId: 16 },
  { id: 47, name: "Overland Park", stateId: 16 },
  { id: 48, name: "Kansas City", stateId: 16 },
  { id: 49, name: "Louisville", stateId: 17 },
  { id: 50, name: "Lexington", stateId: 17 },
  { id: 51, name: "Bowling Green", stateId: 17 },
  { id: 52, name: "New Orleans", stateId: 18 },
  { id: 53, name: "Baton Rouge", stateId: 18 },
  { id: 54, name: "Shreveport", stateId: 18 },
  { id: 55, name: "Portland", stateId: 19 },
  { id: 56, name: "Lewiston", stateId: 19 },
  { id: 57, name: "Bangor", stateId: 19 },
  { id: 58, name: "Baltimore", stateId: 20 },
  { id: 59, name: "Frederick", stateId: 20 },
  { id: 60, name: "Rockville", stateId: 20 },
  { id: 61, name: "Boston", stateId: 21 },
  { id: 62, name: "Worcester", stateId: 21 },
  { id: 63, name: "Springfield", stateId: 21 },
  { id: 64, name: "Detroit", stateId: 22 },
  { id: 65, name: "Grand Rapids", stateId: 22 },
  { id: 66, name: "Warren", stateId: 22 },
  { id: 67, name: "Minneapolis", stateId: 23 },
  { id: 68, name: "St. Paul", stateId: 23 },
  { id: 69, name: "Rochester", stateId: 23 },
  { id: 70, name: "Jackson", stateId: 24 },
  { id: 71, name: "Gulfport", stateId: 24 },
  { id: 72, name: "Southaven", stateId: 24 },
  { id: 73, name: "Kansas City", stateId: 25 },
  { id: 74, name: "St. Louis", stateId: 25 },
  { id: 75, name: "Springfield", stateId: 25 },
  { id: 76, name: "Billings", stateId: 26 },
  { id: 77, name: "Missoula", stateId: 26 },
  { id: 78, name: "Great Falls", stateId: 26 },
  { id: 79, name: "Omaha", stateId: 27 },
  { id: 80, name: "Lincoln", stateId: 27 },
  { id: 81, name: "Bellevue", stateId: 27 },
  { id: 82, name: "Las Vegas", stateId: 28 },
  { id: 83, name: "Henderson", stateId: 28 },
  { id: 84, name: "Reno", stateId: 28 },
  { id: 85, name: "Manchester", stateId: 29 },
  { id: 86, name: "Nashua", stateId: 29 },
  { id: 87, name: "Concord", stateId: 29 },
  { id: 88, name: "Newark", stateId: 30 },
  { id: 89, name: "Jersey City", stateId: 30 },
  { id: 90, name: "Paterson", stateId: 30 },
  { id: 91, name: "Albuquerque", stateId: 31 },
  { id: 92, name: "Las Cruces", stateId: 31 },
  { id: 93, name: "Rio Rancho", stateId: 31 },
  { id: 94, name: "New York", stateId: 32 },
  { id: 95, name: "Buffalo", stateId: 32 },
  { id: 96, name: "Rochester", stateId: 32 },
  { id: 97, name: "Charlotte", stateId: 33 },
  { id: 98, name: "Raleigh", stateId: 33 },
  { id: 99, name: "Greensboro", stateId: 33 },
  { id: 100, name: "Fargo", stateId: 34 },
  { id: 101, name: "Bismarck", stateId: 34 },
  { id: 102, name: "Grand Forks", stateId: 34 },
  { id: 103, name: "Columbus", stateId: 35 },
  { id: 104, name: "Cleveland", stateId: 35 },
  { id: 105, name: "Cincinnati", stateId: 35 },
  { id: 106, name: "Oklahoma City", stateId: 36 },
  { id: 107, name: "Tulsa", stateId: 36 },
  { id: 108, name: "Norman", stateId: 36 },
  { id: 109, name: "Portland", stateId: 37 },
  { id: 110, name: "Lewiston", stateId: 37 },
  { id: 111, name: "Bangor", stateId: 37 },
  { id: 112, name: "Philadelphia", stateId: 38 },
  { id: 113, name: "Pittsburgh", stateId: 38 },
  { id: 114, name: "Allentown", stateId: 38 },
  { id: 115, name: "Providence", stateId: 39 },
  { id: 116, name: "Warwick", stateId: 39 },
  { id: 117, name: "Cranston", stateId: 39 },
  { id: 118, name: "Columbia", stateId: 40 },
  { id: 119, name: "Charleston", stateId: 40 },
  { id: 120, name: "North Charleston", stateId: 40 },
  { id: 121, name: "Sioux Falls", stateId: 41 },
  { id: 122, name: "Rapid City", stateId: 41 },
  { id: 123, name: "Aberdeen", stateId: 41 },
  { id: 124, name: "Memphis", stateId: 42 },
  { id: 125, name: "Nashville", stateId: 42 },
  { id: 126, name: "Knoxville", stateId: 42 },
  { id: 127, name: "Houston", stateId: 43 },
  { id: 128, name: "San Antonio", stateId: 43 },
  { id: 129, name: "Dallas", stateId: 43 },
  { id: 130, name: "Salt Lake City", stateId: 44 },
  { id: 131, name: "West Valley City", stateId: 44 },
  { id: 132, name: "Provo", stateId: 44 },
  { id: 133, name: "Burlington", stateId: 45 },
  { id: 134, name: "South Burlington", stateId: 45 },
  { id: 135, name: "Rutland", stateId: 45 },
  { id: 136, name: "Virginia Beach", stateId: 46 },
  { id: 137, name: "Norfolk", stateId: 46 },
  { id: 138, name: "Chesapeake", stateId: 46 },
  { id: 139, name: "Seattle", stateId: 47 },
  { id: 140, name: "Spokane", stateId: 47 },
  { id: 141, name: "Tacoma", stateId: 47 },
  { id: 142, name: "Charleston", stateId: 48 },
  { id: 143, name: "Huntington", stateId: 48 },
  { id: 144, name: "Parkersburg", stateId: 48 },
  { id: 145, name: "Milwaukee", stateId: 49 },
  { id: 146, name: "Madison", stateId: 49 },
  { id: 147, name: "Green Bay", stateId: 49 },
  { id: 148, name: "Cheyenne", stateId: 50 },
  { id: 149, name: "Casper", stateId: 50 },
  { id: 150, name: "Laramie", stateId: 50 },
] as const;
