import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();
  const { data: session, status } = useSession();

  if (
    status === "authenticated" &&
    session !== null &&
    session.user !== null &&
    router.isReady === true
  ) {
    router.push("/dashboard");
  }

  return (
    <>
      <Head>
        <title>yummy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            yu<span className="text-[hsl(280,100%,70%)]">mm</span>y
          </h1>
          <div className="flex flex-col items-center gap-2">
            <div className="flex flex-col items-center justify-center gap-4">
              <p className="text-center text-2xl text-white">
                {session && session?.user && (
                  <span>Logged in as {session.user.name}</span>
                )}
              </p>
              <button
                className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
                onClick={
                  session
                    ? () => signOut()
                    : () =>
                        signIn("auth0", {
                          callbackUrl: "/dashboard",
                        })
                }
              >
                Sign in
              </button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
