#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd "$(dirname $0)/.."

LOCKFILE_CHANGED_LINES=`git diff HEAD@{1} --stat -- pnpm-lock.yaml | wc -l`
if [ -z "${CI}" ] && [ $LOCKFILE_CHANGED_LINES -gt 0 ];
then
    echo "Detected changes to pnpm-lock.yaml. Reinstalling packages..."
    pnpm i
fi

# Regenerate prisma client + run migrations when relevant files have changed
PRISMA_CHANGED_LINES=`git diff HEAD@{1} --stat -- packages/prisma-client/prisma | wc -l`
if [ -z "${CI}" ] && [ $PRISMA_CHANGED_LINES -gt 0 ];
then
    echo "Detected changes to Prisma schema or migration files. Regenerating client and applying migrations..."
    # Ensure packages are installed
    pnpm i
    pnpm run db:deploy && pnpm  db:generate
fi

cd -
