name: Upstash Keep Alive

on:
  schedule:
    # Run at 12:00 UTC every day
    - cron: '0 12 * * *'

jobs:
  curl-command:
    runs-on: ubuntu-latest
    
    steps:
    - name: Run curl command
      env:
        UPSTASH_REDIS_URL: ${{ secrets.UPSTASH_REDIS_URL }}
        UPSTASH_BEARER_TOKEN: ${{ secrets.UPSTASH_BEARER_TOKEN }}
      run: |
        curl "$UPSTASH_REDIS_URL" -H "Authorization: Bearer $UPSTASH_BEARER_TOKEN"
